//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIENT.MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Контракт генерации сообщений с именем ShowRoutesResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowRoutes", ReplyAction="*")]
        CLIENT.MyService.ShowRoutesResponse ShowRoutes(CLIENT.MyService.ShowRoutesRequest request);
        string ShowRoutes();
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowRoutes", ReplyAction="*")]
        System.Threading.Tasks.Task<CLIENT.MyService.ShowRoutesResponse> ShowRoutesAsync(CLIENT.MyService.ShowRoutesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем Route_id из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRoutes", ReplyAction="*")]
        CLIENT.MyService.CheckRoutesResponse CheckRoutes(CLIENT.MyService.CheckRoutesRequest request);
        string ShowSeats(string rout_num);
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckRoutes", ReplyAction="*")]
        System.Threading.Tasks.Task<CLIENT.MyService.CheckRoutesResponse> CheckRoutesAsync(CLIENT.MyService.CheckRoutesRequest request);
        string buytickets(string rout, int num);
        string CheckRoutes(string rout_num);

        // CODEGEN: Контракт генерации сообщений с именем Route_id из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowSeats", ReplyAction="*")]
        CLIENT.MyService.ShowSeatsResponse ShowSeats(CLIENT.MyService.ShowSeatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowSeats", ReplyAction="*")]
        System.Threading.Tasks.Task<CLIENT.MyService.ShowSeatsResponse> ShowSeatsAsync(CLIENT.MyService.ShowSeatsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем Route_id из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buytickets", ReplyAction="*")]
        CLIENT.MyService.buyticketsResponse buytickets(CLIENT.MyService.buyticketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buytickets", ReplyAction="*")]
        System.Threading.Tasks.Task<CLIENT.MyService.buyticketsResponse> buyticketsAsync(CLIENT.MyService.buyticketsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowRoutesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowRoutes", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.MyService.ShowRoutesRequestBody Body;
        
        public ShowRoutesRequest() {
        }
        
        public ShowRoutesRequest(CLIENT.MyService.ShowRoutesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowRoutesRequestBody {
        
        public ShowRoutesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowRoutesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowRoutesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.MyService.ShowRoutesResponseBody Body;
        
        public ShowRoutesResponse() {
        }
        
        public ShowRoutesResponse(CLIENT.MyService.ShowRoutesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowRoutesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowRoutesResult;
        
        public ShowRoutesResponseBody() {
        }
        
        public ShowRoutesResponseBody(string ShowRoutesResult) {
            this.ShowRoutesResult = ShowRoutesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckRoutesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckRoutes", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.MyService.CheckRoutesRequestBody Body;
        
        public CheckRoutesRequest() {
        }
        
        public CheckRoutesRequest(CLIENT.MyService.CheckRoutesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckRoutesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Route_id;
        
        public CheckRoutesRequestBody() {
        }
        
        public CheckRoutesRequestBody(string Route_id) {
            this.Route_id = Route_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckRoutesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckRoutesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.MyService.CheckRoutesResponseBody Body;
        
        public CheckRoutesResponse() {
        }
        
        public CheckRoutesResponse(CLIENT.MyService.CheckRoutesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckRoutesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckRoutesResult;
        
        public CheckRoutesResponseBody() {
        }
        
        public CheckRoutesResponseBody(string CheckRoutesResult) {
            this.CheckRoutesResult = CheckRoutesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowSeatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowSeats", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.MyService.ShowSeatsRequestBody Body;
        
        public ShowSeatsRequest() {
        }
        
        public ShowSeatsRequest(CLIENT.MyService.ShowSeatsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowSeatsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Route_id;
        
        public ShowSeatsRequestBody() {
        }
        
        public ShowSeatsRequestBody(string Route_id) {
            this.Route_id = Route_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowSeatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowSeatsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.MyService.ShowSeatsResponseBody Body;
        
        public ShowSeatsResponse() {
        }
        
        public ShowSeatsResponse(CLIENT.MyService.ShowSeatsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowSeatsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowSeatsResult;
        
        public ShowSeatsResponseBody() {
        }
        
        public ShowSeatsResponseBody(string ShowSeatsResult) {
            this.ShowSeatsResult = ShowSeatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buyticketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buytickets", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.MyService.buyticketsRequestBody Body;
        
        public buyticketsRequest() {
        }
        
        public buyticketsRequest(CLIENT.MyService.buyticketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buyticketsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Route_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num;
        
        public buyticketsRequestBody() {
        }
        
        public buyticketsRequestBody(string Route_id, int num) {
            this.Route_id = Route_id;
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buyticketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buyticketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.MyService.buyticketsResponseBody Body;
        
        public buyticketsResponse() {
        }
        
        public buyticketsResponse(CLIENT.MyService.buyticketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buyticketsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string buyticketsResult;
        
        public buyticketsResponseBody() {
        }
        
        public buyticketsResponseBody(string buyticketsResult) {
            this.buyticketsResult = buyticketsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CLIENT.MyService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CLIENT.MyService.WebService1Soap>, CLIENT.MyService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CLIENT.MyService.ShowRoutesResponse CLIENT.MyService.WebService1Soap.ShowRoutes(CLIENT.MyService.ShowRoutesRequest request) {
            return base.Channel.ShowRoutes(request);
        }
        
        public string ShowRoutes() {
            CLIENT.MyService.ShowRoutesRequest inValue = new CLIENT.MyService.ShowRoutesRequest();
            inValue.Body = new CLIENT.MyService.ShowRoutesRequestBody();
            CLIENT.MyService.ShowRoutesResponse retVal = ((CLIENT.MyService.WebService1Soap)(this)).ShowRoutes(inValue);
            return retVal.Body.ShowRoutesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CLIENT.MyService.ShowRoutesResponse> CLIENT.MyService.WebService1Soap.ShowRoutesAsync(CLIENT.MyService.ShowRoutesRequest request) {
            return base.Channel.ShowRoutesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CLIENT.MyService.ShowRoutesResponse> ShowRoutesAsync() {
            CLIENT.MyService.ShowRoutesRequest inValue = new CLIENT.MyService.ShowRoutesRequest();
            inValue.Body = new CLIENT.MyService.ShowRoutesRequestBody();
            return ((CLIENT.MyService.WebService1Soap)(this)).ShowRoutesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CLIENT.MyService.CheckRoutesResponse CLIENT.MyService.WebService1Soap.CheckRoutes(CLIENT.MyService.CheckRoutesRequest request) {
            return base.Channel.CheckRoutes(request);
        }
        
        public string CheckRoutes(string Route_id) {
            CLIENT.MyService.CheckRoutesRequest inValue = new CLIENT.MyService.CheckRoutesRequest();
            inValue.Body = new CLIENT.MyService.CheckRoutesRequestBody();
            inValue.Body.Route_id = Route_id;
            CLIENT.MyService.CheckRoutesResponse retVal = ((CLIENT.MyService.WebService1Soap)(this)).CheckRoutes(inValue);
            return retVal.Body.CheckRoutesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CLIENT.MyService.CheckRoutesResponse> CLIENT.MyService.WebService1Soap.CheckRoutesAsync(CLIENT.MyService.CheckRoutesRequest request) {
            return base.Channel.CheckRoutesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CLIENT.MyService.CheckRoutesResponse> CheckRoutesAsync(string Route_id) {
            CLIENT.MyService.CheckRoutesRequest inValue = new CLIENT.MyService.CheckRoutesRequest();
            inValue.Body = new CLIENT.MyService.CheckRoutesRequestBody();
            inValue.Body.Route_id = Route_id;
            return ((CLIENT.MyService.WebService1Soap)(this)).CheckRoutesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CLIENT.MyService.ShowSeatsResponse CLIENT.MyService.WebService1Soap.ShowSeats(CLIENT.MyService.ShowSeatsRequest request) {
            return base.Channel.ShowSeats(request);
        }
        
        public string ShowSeats(string Route_id) {
            CLIENT.MyService.ShowSeatsRequest inValue = new CLIENT.MyService.ShowSeatsRequest();
            inValue.Body = new CLIENT.MyService.ShowSeatsRequestBody();
            inValue.Body.Route_id = Route_id;
            CLIENT.MyService.ShowSeatsResponse retVal = ((CLIENT.MyService.WebService1Soap)(this)).ShowSeats(inValue);
            return retVal.Body.ShowSeatsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CLIENT.MyService.ShowSeatsResponse> CLIENT.MyService.WebService1Soap.ShowSeatsAsync(CLIENT.MyService.ShowSeatsRequest request) {
            return base.Channel.ShowSeatsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CLIENT.MyService.ShowSeatsResponse> ShowSeatsAsync(string Route_id) {
            CLIENT.MyService.ShowSeatsRequest inValue = new CLIENT.MyService.ShowSeatsRequest();
            inValue.Body = new CLIENT.MyService.ShowSeatsRequestBody();
            inValue.Body.Route_id = Route_id;
            return ((CLIENT.MyService.WebService1Soap)(this)).ShowSeatsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CLIENT.MyService.buyticketsResponse CLIENT.MyService.WebService1Soap.buytickets(CLIENT.MyService.buyticketsRequest request) {
            return base.Channel.buytickets(request);
        }
        
        public string buytickets(string Route_id, int num) {
            CLIENT.MyService.buyticketsRequest inValue = new CLIENT.MyService.buyticketsRequest();
            inValue.Body = new CLIENT.MyService.buyticketsRequestBody();
            inValue.Body.Route_id = Route_id;
            inValue.Body.num = num;
            CLIENT.MyService.buyticketsResponse retVal = ((CLIENT.MyService.WebService1Soap)(this)).buytickets(inValue);
            return retVal.Body.buyticketsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CLIENT.MyService.buyticketsResponse> CLIENT.MyService.WebService1Soap.buyticketsAsync(CLIENT.MyService.buyticketsRequest request) {
            return base.Channel.buyticketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CLIENT.MyService.buyticketsResponse> buyticketsAsync(string Route_id, int num) {
            CLIENT.MyService.buyticketsRequest inValue = new CLIENT.MyService.buyticketsRequest();
            inValue.Body = new CLIENT.MyService.buyticketsRequestBody();
            inValue.Body.Route_id = Route_id;
            inValue.Body.num = num;
            return ((CLIENT.MyService.WebService1Soap)(this)).buyticketsAsync(inValue);
        }
    }
}
